on: pull_request
name: textlint
jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2.3.2
        with:
          node-version: '14'
      - run: npm install
      - name: danger
        uses: yuichielectric/danger-textlint-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
